# Generated by Django 3.0.2 on 2020-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
