# Generated by Django 3.0.2 on 2020-02-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0003_auto_20200203_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
