# Generated by Django 3.0.2 on 2020-02-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0005_auto_20200203_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spicefile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spicefile',
            name='size',
        ),
    ]
